<?php
			$optionsArray = array( 'totals' => array( 'CC_ID' => array( 'totalsType' => '' ),
'EXPEDIENTE' => array( 'totalsType' => '' ),
'EXPEDIENTEREL' => array( 'totalsType' => '' ),
'TIPODOCUMENTO' => array( 'totalsType' => '' ),
'NIT_CEDULA' => array( 'totalsType' => '' ),
'DV' => array( 'totalsType' => '' ),
'NOMBRE_RAZON' => array( 'totalsType' => '' ),
'NOMBRE DE EMPRESA EN EXPEDIENTE DE COBRO COACTIVO' => array( 'totalsType' => '' ),
'CARACTER' => array( 'totalsType' => '' ),
'CIUDAD' => array( 'totalsType' => '' ),
'DIRECCION' => array( 'totalsType' => '' ),
'CLASE_SANCION' => array( 'totalsType' => '' ),
'REMITENTE' => array( 'totalsType' => '' ),
'RESOLUCION_SANCION' => array( 'totalsType' => '' ),
'FECHA _RESOLUCION' => array( 'totalsType' => '' ),
'VALOR_SANCION' => array( 'totalsType' => '' ),
'RECAUDADO_CONSIGNACIONES' => array( 'totalsType' => '' ),
'RECAUDADO_TITULOS_JUDICIALES' => array( 'totalsType' => '' ),
'FECHA_EJECUTORIA' => array( 'totalsType' => '' ),
'FECHA_MANDAMIENTO_PAGO' => array( 'totalsType' => '' ),
'FECHA_NOTIFICACION_MANDAMIENTO' => array( 'totalsType' => '' ),
'ULTMA_ACTUACION' => array( 'totalsType' => '' ),
'FECHA_ACTUACION' => array( 'totalsType' => '' ),
'FECHA_PROX_ACTUACION' => array( 'totalsType' => '' ),
'ESTADO' => array( 'totalsType' => '' ),
'AUTO_CANCELACION' => array( 'totalsType' => '' ),
'ABOGADO' => array( 'totalsType' => '' ),
'ABOGADO_RESP' => array( 'totalsType' => '' ),
'FECHA_PRESCRIPCION' => array( 'totalsType' => '' ),
'DIAS FALTANTES PARA PRESCRIBIR' => array( 'totalsType' => '' ),
'TIEMPO_PRES' => array( 'totalsType' => '' ),
'OBS_PROC_PAG_SN_EXTRC' => array( 'totalsType' => '' ),
'ULTIMA_ACTUACION' => array( 'totalsType' => '' ),
'COMENTARIO_UA' => array( 'totalsType' => '' ),
'ACUERDO_PAGO' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'CC_ID',
'EXPEDIENTE',
'NIT_CEDULA',
'DV',
'NOMBRE DE EMPRESA EN EXPEDIENTE DE COBRO COACTIVO',
'CIUDAD',
'DIRECCION',
'CLASE_SANCION',
'REMITENTE',
'VALOR_SANCION',
'FECHA_EJECUTORIA',
'FECHA_MANDAMIENTO_PAGO',
'FECHA_NOTIFICACION_MANDAMIENTO',
'ESTADO',
'FECHA_PRESCRIPCION',
'TIEMPO_PRES',
'ULTIMA_ACTUACION',
'COMENTARIO_UA',
'ACUERDO_PAGO',
'ABOGADO_RESP',
'EXPEDIENTEREL',
'TIPODOCUMENTO',
'CARACTER' ),
'exportFields' => array( 'CC_ID',
'EXPEDIENTE',
'DV',
'NOMBRE DE EMPRESA EN EXPEDIENTE DE COBRO COACTIVO',
'CIUDAD',
'DIRECCION',
'CLASE_SANCION',
'REMITENTE',
'ESTADO',
'TIEMPO_PRES',
'NIT_CEDULA',
'VALOR_SANCION',
'FECHA_EJECUTORIA',
'FECHA_MANDAMIENTO_PAGO',
'FECHA_NOTIFICACION_MANDAMIENTO',
'FECHA_PRESCRIPCION',
'ULTIMA_ACTUACION',
'COMENTARIO_UA',
'ACUERDO_PAGO',
'ABOGADO_RESP',
'EXPEDIENTEREL',
'TIPODOCUMENTO',
'CARACTER' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'CC_ID' => array( 'export_field' ),
'EXPEDIENTE' => array( 'export_field1' ),
'NIT_CEDULA' => array( 'export_field2' ),
'DV' => array( 'export_field3' ),
'NOMBRE DE EMPRESA EN EXPEDIENTE DE COBRO COACTIVO' => array( 'export_field5' ),
'CIUDAD' => array( 'export_field6' ),
'DIRECCION' => array( 'export_field7' ),
'CLASE_SANCION' => array( 'export_field8' ),
'REMITENTE' => array( 'export_field9' ),
'VALOR_SANCION' => array( 'export_field12' ),
'FECHA_EJECUTORIA' => array( 'export_field15' ),
'FECHA_MANDAMIENTO_PAGO' => array( 'export_field16' ),
'FECHA_NOTIFICACION_MANDAMIENTO' => array( 'export_field17' ),
'ESTADO' => array( 'export_field19' ),
'FECHA_PRESCRIPCION' => array( 'export_field22' ),
'TIEMPO_PRES' => array( 'export_field24' ),
'ULTIMA_ACTUACION' => array( 'export_field10' ),
'COMENTARIO_UA' => array( 'export_field11' ),
'ACUERDO_PAGO' => array( 'export_field13' ),
'ABOGADO_RESP' => array( 'export_field20' ),
'EXPEDIENTEREL' => array( 'export_field4' ),
'TIPODOCUMENTO' => array( 'export_field14' ),
'CARACTER' => array( 'export_field18' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field3',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field19',
'export_field24',
'export_field2',
'export_field12',
'export_field15',
'export_field16',
'export_field17',
'export_field22',
'export_field10',
'export_field11',
'export_field13',
'export_field20',
'export_field4',
'export_field14',
'export_field18' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field3' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field19' => 'grid',
'export_field24' => 'grid',
'export_field2' => 'grid',
'export_field12' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field22' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field13' => 'grid',
'export_field20' => 'grid',
'export_field4' => 'grid',
'export_field14' => 'grid',
'export_field18' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field12',
'export_field15',
'export_field16',
'export_field17',
'export_field19',
'export_field22',
'export_field24',
'export_field10',
'export_field11',
'export_field13',
'export_field20',
'export_field4',
'export_field14',
'export_field18' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field3',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field19',
'export_field24',
'export_field2',
'export_field12',
'export_field15',
'export_field16',
'export_field17',
'export_field22',
'export_field10',
'export_field11',
'export_field13',
'export_field20',
'export_field4',
'export_field14',
'export_field18' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'CC_ID',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'EXPEDIENTE',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'NIT_CEDULA',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'DV',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'NOMBRE DE EMPRESA EN EXPEDIENTE DE COBRO COACTIVO',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'CIUDAD',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'DIRECCION',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'CLASE_SANCION',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'REMITENTE',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'VALOR_SANCION',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'FECHA_EJECUTORIA',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'FECHA_MANDAMIENTO_PAGO',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'FECHA_NOTIFICACION_MANDAMIENTO',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'ESTADO',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'FECHA_PRESCRIPCION',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'TIEMPO_PRES',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'ULTIMA_ACTUACION',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'COMENTARIO_UA',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'ACUERDO_PAGO',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'ABOGADO_RESP',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'EXPEDIENTEREL',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'TIPODOCUMENTO',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'CARACTER',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>