<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'CC_ID',
'EXPEDIENTE',
'NIT_CEDULA',
'DV',
'NOMBRE_RAZON',
'NOMBRE DE EMPRESA EN EXPEDIENTE DE COBRO COACTIVO',
'CIUDAD',
'DIRECCION',
'CLASE_SANCION',
'REMITENTE',
'RESOLUCION_SANCION',
'FECHA _RESOLUCION',
'VALOR_SANCION',
'RECAUDADO_CONSIGNACIONES',
'RECAUDADO_TITULOS_JUDICIALES',
'FECHA_EJECUTORIA',
'FECHA_MANDAMIENTO_PAGO',
'FECHA_NOTIFICACION_MANDAMIENTO',
'ULTMA_ACTUACION',
'ESTADO',
'AUTO_CANCELACION',
'ABOGADO',
'FECHA_PRESCRIPCION',
'DIAS FALTANTES PARA PRESCRIBIR',
'TIEMPO_PRES',
'OBS_PROC_PAG_SN_EXTRC',
'ULTIMA_ACTUACION',
'COMENTARIO_UA',
'ACUERDO_PAGO',
'FECHA_ACTUACION',
'FECHA_PROX_ACTUACION',
'ABOGADO_RESP',
'EXPEDIENTEREL',
'TIPODOCUMENTO',
'CARACTER' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'CC_ID' => array( 'integrated_search_field' ),
'EXPEDIENTE' => array( 'integrated_search_field1' ),
'NIT_CEDULA' => array( 'integrated_search_field2' ),
'DV' => array( 'integrated_search_field3' ),
'NOMBRE_RAZON' => array( 'integrated_search_field4' ),
'NOMBRE DE EMPRESA EN EXPEDIENTE DE COBRO COACTIVO' => array( 'integrated_search_field5' ),
'CIUDAD' => array( 'integrated_search_field6' ),
'DIRECCION' => array( 'integrated_search_field7' ),
'CLASE_SANCION' => array( 'integrated_search_field8' ),
'REMITENTE' => array( 'integrated_search_field9' ),
'RESOLUCION_SANCION' => array( 'integrated_search_field10' ),
'FECHA _RESOLUCION' => array( 'integrated_search_field11' ),
'VALOR_SANCION' => array( 'integrated_search_field12' ),
'RECAUDADO_CONSIGNACIONES' => array( 'integrated_search_field13' ),
'RECAUDADO_TITULOS_JUDICIALES' => array( 'integrated_search_field14' ),
'FECHA_EJECUTORIA' => array( 'integrated_search_field15' ),
'FECHA_MANDAMIENTO_PAGO' => array( 'integrated_search_field16' ),
'FECHA_NOTIFICACION_MANDAMIENTO' => array( 'integrated_search_field17' ),
'ULTMA_ACTUACION' => array( 'integrated_search_field18' ),
'ESTADO' => array( 'integrated_search_field19' ),
'AUTO_CANCELACION' => array( 'integrated_search_field20' ),
'ABOGADO' => array( 'integrated_search_field21' ),
'FECHA_PRESCRIPCION' => array( 'integrated_search_field22' ),
'DIAS FALTANTES PARA PRESCRIBIR' => array( 'integrated_search_field23' ),
'TIEMPO_PRES' => array( 'integrated_search_field24' ),
'OBS_PROC_PAG_SN_EXTRC' => array( 'integrated_search_field25' ),
'ULTIMA_ACTUACION' => array( 'integrated_search_field26' ),
'COMENTARIO_UA' => array( 'integrated_search_field27' ),
'ACUERDO_PAGO' => array( 'integrated_search_field28' ),
'FECHA_ACTUACION' => array( 'integrated_search_field29' ),
'FECHA_PROX_ACTUACION' => array( 'integrated_search_field30' ),
'ABOGADO_RESP' => array( 'integrated_search_field31' ),
'EXPEDIENTEREL' => array( 'integrated_search_field32' ),
'TIPODOCUMENTO' => array( 'integrated_search_field33' ),
'CARACTER' => array( 'integrated_search_field34' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'search_header' ),
'above-grid' => array(  ),
'below-grid' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'grid' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field3',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field19',
'integrated_search_field21',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field2',
'integrated_search_field4',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field20',
'integrated_search_field22',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'search_header' => 'top',
'search_search' => 'below-grid',
'search_reset' => 'below-grid',
'search_back_list' => 'below-grid',
'search_cancel' => 'below-grid',
'integrated_search_field' => 'grid',
'integrated_search_field1' => 'grid',
'integrated_search_field3' => 'grid',
'integrated_search_field5' => 'grid',
'integrated_search_field6' => 'grid',
'integrated_search_field7' => 'grid',
'integrated_search_field8' => 'grid',
'integrated_search_field9' => 'grid',
'integrated_search_field19' => 'grid',
'integrated_search_field21' => 'grid',
'integrated_search_field23' => 'grid',
'integrated_search_field24' => 'grid',
'integrated_search_field25' => 'grid',
'integrated_search_field2' => 'grid',
'integrated_search_field4' => 'grid',
'integrated_search_field10' => 'grid',
'integrated_search_field11' => 'grid',
'integrated_search_field12' => 'grid',
'integrated_search_field13' => 'grid',
'integrated_search_field14' => 'grid',
'integrated_search_field15' => 'grid',
'integrated_search_field16' => 'grid',
'integrated_search_field17' => 'grid',
'integrated_search_field18' => 'grid',
'integrated_search_field20' => 'grid',
'integrated_search_field22' => 'grid',
'integrated_search_field26' => 'grid',
'integrated_search_field27' => 'grid',
'integrated_search_field28' => 'grid',
'integrated_search_field29' => 'grid',
'integrated_search_field30' => 'grid',
'integrated_search_field31' => 'grid',
'integrated_search_field32' => 'grid',
'integrated_search_field33' => 'grid',
'integrated_search_field34' => 'grid' ),
'itemLocations' => array( 'integrated_search_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field5' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field6' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field7' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field8' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field9' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field19' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field21' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field23' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field24' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field25' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field4' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field10' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field11' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field12' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field13' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field14' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field15' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field16' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field17' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field18' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field20' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field22' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field26' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field27' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field28' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field29' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field30' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field31' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field32' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field33' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field34' => array( 'location' => 'grid',
'cellId' => 'c3' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'search_header' => array( 'search_header' ),
'search_reset' => array( 'search_reset' ),
'search_back_list' => array( 'search_back_list' ),
'search_search' => array( 'search_search' ),
'search_cancel' => array( 'search_cancel' ),
'integrated_search_field' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field3',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field19',
'integrated_search_field21',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field2',
'integrated_search_field4',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field20',
'integrated_search_field22',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'search',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'search',
'type' => 'search',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'search-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'search-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'search-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-search',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field3',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field19',
'integrated_search_field21',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field2',
'integrated_search_field4',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field20',
'integrated_search_field22',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'separateLabels' => false ) ),
'items' => array( 'search_header' => array( 'type' => 'search_header' ),
'search_reset' => array( 'type' => 'search_reset' ),
'search_back_list' => array( 'type' => 'search_back_list' ),
'search_search' => array( 'type' => 'search_search' ),
'search_cancel' => array( 'type' => 'search_cancel' ),
'integrated_search_field' => array( 'field' => 'CC_ID',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field1' => array( 'field' => 'EXPEDIENTE',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field2' => array( 'field' => 'NIT_CEDULA',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field3' => array( 'field' => 'DV',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field4' => array( 'field' => 'NOMBRE_RAZON',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field5' => array( 'field' => 'NOMBRE DE EMPRESA EN EXPEDIENTE DE COBRO COACTIVO',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field6' => array( 'field' => 'CIUDAD',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field7' => array( 'field' => 'DIRECCION',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field8' => array( 'field' => 'CLASE_SANCION',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field9' => array( 'field' => 'REMITENTE',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field10' => array( 'field' => 'RESOLUCION_SANCION',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field11' => array( 'field' => 'FECHA _RESOLUCION',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field12' => array( 'field' => 'VALOR_SANCION',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field13' => array( 'field' => 'RECAUDADO_CONSIGNACIONES',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field14' => array( 'field' => 'RECAUDADO_TITULOS_JUDICIALES',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field15' => array( 'field' => 'FECHA_EJECUTORIA',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field16' => array( 'field' => 'FECHA_MANDAMIENTO_PAGO',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field17' => array( 'field' => 'FECHA_NOTIFICACION_MANDAMIENTO',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field18' => array( 'field' => 'ULTMA_ACTUACION',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field19' => array( 'field' => 'ESTADO',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field20' => array( 'field' => 'AUTO_CANCELACION',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field21' => array( 'field' => 'ABOGADO',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field22' => array( 'field' => 'FECHA_PRESCRIPCION',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field23' => array( 'field' => 'DIAS FALTANTES PARA PRESCRIBIR',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field24' => array( 'field' => 'TIEMPO_PRES',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field25' => array( 'field' => 'OBS_PROC_PAG_SN_EXTRC',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field26' => array( 'field' => 'ULTIMA_ACTUACION',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field27' => array( 'field' => 'COMENTARIO_UA',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field28' => array( 'field' => 'ACUERDO_PAGO',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field29' => array( 'field' => 'FECHA_ACTUACION',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field30' => array( 'field' => 'FECHA_PROX_ACTUACION',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field31' => array( 'field' => 'ABOGADO_RESP',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field32' => array( 'field' => 'EXPEDIENTEREL',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field33' => array( 'field' => 'TIPODOCUMENTO',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field34' => array( 'field' => 'CARACTER',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>