<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'details' => array( 'rj_master_audiencias' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'rj_master_anexos' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'rj_master_provision_contable' => array( 'displayPreview' => 2,
'previewPageId' => '' ) ),
'fields' => array( 'gridFields' => array( 'tipo_proceso_fk',
'id_oaj',
'carpeta',
'CAJA',
'ekogui_id',
'fecha_radicado_ekogui',
'radicado_ekogui',
'fecha_proxima_actualizacion',
'observacion_perder_caso',
'propabilidad_perder_caso',
'valor_provision_contable',
'fecha_provision_contable',
'etapa_judicial',
'fecha_constestacion_demanda',
'contestacion_demanda',
'fecha_radicado_oaj',
'fecha_admision_demanda',
'apoderado_oaj',
'cuantia_pretension',
'pretenciones',
'fecha_presentacion_demanda',
'despacho_actual',
'nom_demandado',
'apoderado_demandante',
'nom_demandante',
'doc_demandante',
'causas',
'municipio_fk',
'hechos',
'estado_id_fk',
'calidad',
'num_proceso',
'estado_proceso' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'tipo_proceso_fk' => array( 'integrated_edit_field' ),
'id_oaj' => array( 'integrated_edit_field15' ),
'carpeta' => array( 'integrated_edit_field30' ),
'CAJA' => array( 'integrated_edit_field31' ),
'ekogui_id' => array( 'integrated_edit_field29' ),
'fecha_radicado_ekogui' => array( 'integrated_edit_field28' ),
'radicado_ekogui' => array( 'integrated_edit_field27' ),
'fecha_proxima_actualizacion' => array( 'integrated_edit_field26' ),
'observacion_perder_caso' => array( 'integrated_edit_field25' ),
'propabilidad_perder_caso' => array( 'integrated_edit_field24' ),
'valor_provision_contable' => array( 'integrated_edit_field23' ),
'fecha_provision_contable' => array( 'integrated_edit_field22' ),
'etapa_judicial' => array( 'integrated_edit_field21' ),
'fecha_constestacion_demanda' => array( 'integrated_edit_field20' ),
'contestacion_demanda' => array( 'integrated_edit_field19' ),
'fecha_radicado_oaj' => array( 'integrated_edit_field18' ),
'fecha_admision_demanda' => array( 'integrated_edit_field17' ),
'apoderado_oaj' => array( 'integrated_edit_field16' ),
'cuantia_pretension' => array( 'integrated_edit_field13' ),
'pretenciones' => array( 'integrated_edit_field12' ),
'fecha_presentacion_demanda' => array( 'integrated_edit_field11' ),
'despacho_actual' => array( 'integrated_edit_field10' ),
'nom_demandado' => array( 'integrated_edit_field9' ),
'apoderado_demandante' => array( 'integrated_edit_field8' ),
'nom_demandante' => array( 'integrated_edit_field7' ),
'doc_demandante' => array( 'integrated_edit_field6' ),
'causas' => array( 'integrated_edit_field5' ),
'municipio_fk' => array( 'integrated_edit_field4' ),
'hechos' => array( 'integrated_edit_field3' ),
'estado_id_fk' => array( 'integrated_edit_field2' ),
'calidad' => array( 'integrated_edit_field14' ),
'num_proceso' => array( 'integrated_edit_field1' ),
'estado_proceso' => array( 'integrated_edit_field32' ) ) ),
'pageLinks' => array( 'edit' => true,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array( 'expand_menu_button',
'collapse_button',
'loginform_login',
'username_button' ),
'left' => array( 'logo1',
'expand_button',
'menu' ),
'top' => array( 'view_header' ),
'above-grid' => array(  ),
'below-grid' => array( 'view_back_list',
'view_close',
'hamburger' ),
'grid' => array( 'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field1',
'integrated_edit_field14',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field15',
'integrated_edit_field' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'view_header' => 'top',
'view_back_list' => 'below-grid',
'view_close' => 'below-grid',
'hamburger' => 'below-grid',
'integrated_edit_field30' => 'grid',
'integrated_edit_field31' => 'grid',
'integrated_edit_field32' => 'grid',
'integrated_edit_field1' => 'grid',
'integrated_edit_field14' => 'grid',
'integrated_edit_field2' => 'grid',
'integrated_edit_field3' => 'grid',
'integrated_edit_field4' => 'grid',
'integrated_edit_field5' => 'grid',
'integrated_edit_field6' => 'grid',
'integrated_edit_field7' => 'grid',
'integrated_edit_field8' => 'grid',
'integrated_edit_field9' => 'grid',
'integrated_edit_field10' => 'grid',
'integrated_edit_field11' => 'grid',
'integrated_edit_field12' => 'grid',
'integrated_edit_field13' => 'grid',
'integrated_edit_field16' => 'grid',
'integrated_edit_field17' => 'grid',
'integrated_edit_field18' => 'grid',
'integrated_edit_field19' => 'grid',
'integrated_edit_field20' => 'grid',
'integrated_edit_field21' => 'grid',
'integrated_edit_field22' => 'grid',
'integrated_edit_field23' => 'grid',
'integrated_edit_field24' => 'grid',
'integrated_edit_field25' => 'grid',
'integrated_edit_field26' => 'grid',
'integrated_edit_field27' => 'grid',
'integrated_edit_field28' => 'grid',
'integrated_edit_field29' => 'grid',
'integrated_edit_field15' => 'grid',
'integrated_edit_field' => 'grid' ),
'itemLocations' => array( 'integrated_edit_field30' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field31' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_edit_field32' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c8' ),
'integrated_edit_field14' => array( 'location' => 'grid',
'cellId' => 'c9' ),
'integrated_edit_field2' => array( 'location' => 'grid',
'cellId' => 'c10' ),
'integrated_edit_field3' => array( 'location' => 'grid',
'cellId' => 'c11' ),
'integrated_edit_field4' => array( 'location' => 'grid',
'cellId' => 'c14' ),
'integrated_edit_field5' => array( 'location' => 'grid',
'cellId' => 'c15' ),
'integrated_edit_field6' => array( 'location' => 'grid',
'cellId' => 'c17' ),
'integrated_edit_field7' => array( 'location' => 'grid',
'cellId' => 'c18' ),
'integrated_edit_field8' => array( 'location' => 'grid',
'cellId' => 'c19' ),
'integrated_edit_field9' => array( 'location' => 'grid',
'cellId' => 'c20' ),
'integrated_edit_field10' => array( 'location' => 'grid',
'cellId' => 'c21' ),
'integrated_edit_field11' => array( 'location' => 'grid',
'cellId' => 'c22' ),
'integrated_edit_field12' => array( 'location' => 'grid',
'cellId' => 'c23' ),
'integrated_edit_field13' => array( 'location' => 'grid',
'cellId' => 'c26' ),
'integrated_edit_field16' => array( 'location' => 'grid',
'cellId' => 'c29' ),
'integrated_edit_field17' => array( 'location' => 'grid',
'cellId' => 'c32' ),
'integrated_edit_field18' => array( 'location' => 'grid',
'cellId' => 'c33' ),
'integrated_edit_field19' => array( 'location' => 'grid',
'cellId' => 'c34' ),
'integrated_edit_field20' => array( 'location' => 'grid',
'cellId' => 'c35' ),
'integrated_edit_field21' => array( 'location' => 'grid',
'cellId' => 'c36' ),
'integrated_edit_field22' => array( 'location' => 'grid',
'cellId' => 'c38' ),
'integrated_edit_field23' => array( 'location' => 'grid',
'cellId' => 'c39' ),
'integrated_edit_field24' => array( 'location' => 'grid',
'cellId' => 'c41' ),
'integrated_edit_field25' => array( 'location' => 'grid',
'cellId' => 'c42' ),
'integrated_edit_field26' => array( 'location' => 'grid',
'cellId' => 'c44' ),
'integrated_edit_field27' => array( 'location' => 'grid',
'cellId' => 'c47' ),
'integrated_edit_field28' => array( 'location' => 'grid',
'cellId' => 'c48' ),
'integrated_edit_field29' => array( 'location' => 'grid',
'cellId' => 'c49' ),
'integrated_edit_field15' => array( 'location' => 'grid',
'cellId' => 'c12' ),
'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c13' ) ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'view_header' => array( 'view_header' ),
'view_back_list' => array( 'view_back_list' ),
'view_close' => array( 'view_close' ),
'hamburger' => array( 'hamburger' ),
'view_edit' => array( 'view_edit' ),
'integrated_edit_field' => array( 'integrated_edit_field',
'integrated_edit_field15',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field29',
'integrated_edit_field28',
'integrated_edit_field27',
'integrated_edit_field26',
'integrated_edit_field25',
'integrated_edit_field24',
'integrated_edit_field23',
'integrated_edit_field22',
'integrated_edit_field21',
'integrated_edit_field20',
'integrated_edit_field19',
'integrated_edit_field18',
'integrated_edit_field17',
'integrated_edit_field16',
'integrated_edit_field13',
'integrated_edit_field12',
'integrated_edit_field11',
'integrated_edit_field10',
'integrated_edit_field9',
'integrated_edit_field8',
'integrated_edit_field7',
'integrated_edit_field6',
'integrated_edit_field5',
'integrated_edit_field4',
'integrated_edit_field3',
'integrated_edit_field2',
'integrated_edit_field14',
'integrated_edit_field1',
'integrated_edit_field32' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'collapse_button' => array( 'collapse_button' ),
'logo' => array( 'logo1' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'adminarea_link' => array( 'adminarea_link' ),
'userinfo_link' => array( 'userinfo_link' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c12' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c24' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field14' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c14' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c15' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c16' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c17' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c18' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c19' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c20' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c21' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c22' => array( 'cols' => array( 2 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c23' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c26' => array( 'cols' => array( 0 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c27' => array( 'cols' => array( 1 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c28' => array( 'cols' => array( 2 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c29' => array( 'cols' => array( 0 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c30' => array( 'cols' => array( 1 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c31' => array( 'cols' => array( 2 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c32' => array( 'cols' => array( 0 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c33' => array( 'cols' => array( 1 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field18' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c34' => array( 'cols' => array( 2 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field19' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c35' => array( 'cols' => array( 0 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field20' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c36' => array( 'cols' => array( 1 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field21' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c37' => array( 'cols' => array( 2 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c38' => array( 'cols' => array( 0 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field22' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c39' => array( 'cols' => array( 1 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field23' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c40' => array( 'cols' => array( 2 ),
'rows' => array( 11 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c41' => array( 'cols' => array( 0 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field24' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c42' => array( 'cols' => array( 1,
2 ),
'rows' => array( 12 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field25' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c44' => array( 'cols' => array( 0 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field26' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c45' => array( 'cols' => array( 1 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c46' => array( 'cols' => array( 2 ),
'rows' => array( 13 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c47' => array( 'cols' => array( 0 ),
'rows' => array( 14 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field27' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c48' => array( 'cols' => array( 1 ),
'rows' => array( 14 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field28' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c49' => array( 'cols' => array( 2 ),
'rows' => array( 14 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field29' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0 ),
'rows' => array( 15 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field30' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 1 ),
'rows' => array( 15 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field31' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 2 ),
'rows' => array( 15 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 16 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field32' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 17 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'view',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'view',
'type' => 'view',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'leftbar-top-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'view-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'view-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'view-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_back_list',
'view_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c12' ),
array( 'cell' => 'c13' ),
array( 'cell' => 'c24' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ),
array( 'cell' => 'c10' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c11',
'colspan' => 3 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c14' ),
array( 'cell' => 'c15' ),
array( 'cell' => 'c16' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c17' ),
array( 'cell' => 'c18' ),
array( 'cell' => 'c19' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c20' ),
array( 'cell' => 'c21' ),
array( 'cell' => 'c22' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c23',
'colspan' => 3 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c26' ),
array( 'cell' => 'c27' ),
array( 'cell' => 'c28' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c29' ),
array( 'cell' => 'c30' ),
array( 'cell' => 'c31' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c32' ),
array( 'cell' => 'c33' ),
array( 'cell' => 'c34' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c35' ),
array( 'cell' => 'c36' ),
array( 'cell' => 'c37' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c38' ),
array( 'cell' => 'c39' ),
array( 'cell' => 'c40' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c41' ),
array( 'cell' => 'c42',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c44' ),
array( 'cell' => 'c45' ),
array( 'cell' => 'c46' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c47' ),
array( 'cell' => 'c48' ),
array( 'cell' => 'c49' ) ) ),
array( 'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c4' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c5',
'colspan' => 3 ) ) ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field30' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c3',
'items' => array(  ) ),
'c4' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field31' ) ),
'c5' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field32' ),
'useFullWidth' => true ),
'c8' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field1' ) ),
'c9' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field14' ) ),
'c10' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field2' ) ),
'c11' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field3' ),
'useFullWidth' => true ),
'c14' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field4' ) ),
'c15' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field5' ) ),
'c16' => array( 'model' => 'c3',
'items' => array(  ) ),
'c17' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field6' ) ),
'c18' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field7' ) ),
'c19' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field8' ) ),
'c20' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field9' ) ),
'c21' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field10' ) ),
'c22' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field11' ) ),
'c23' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field12' ),
'useFullWidth' => true ),
'c26' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field13' ) ),
'c27' => array( 'model' => 'c3',
'items' => array(  ) ),
'c28' => array( 'model' => 'c3',
'items' => array(  ) ),
'c29' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field16' ) ),
'c30' => array( 'model' => 'c3',
'items' => array(  ) ),
'c31' => array( 'model' => 'c3',
'items' => array(  ) ),
'c32' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field17' ) ),
'c33' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field18' ) ),
'c34' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field19' ) ),
'c35' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field20' ) ),
'c36' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field21' ) ),
'c37' => array( 'model' => 'c3',
'items' => array(  ) ),
'c38' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field22' ) ),
'c39' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field23' ) ),
'c40' => array( 'model' => 'c3',
'items' => array(  ) ),
'c41' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field24' ) ),
'c42' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field25' ) ),
'c44' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field26' ) ),
'c45' => array( 'model' => 'c3',
'items' => array(  ) ),
'c46' => array( 'model' => 'c3',
'items' => array(  ) ),
'c47' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field27' ) ),
'c48' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field28' ) ),
'c49' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field29' ) ),
'c12' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field15' ) ),
'c13' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field' ) ),
'c24' => array( 'model' => 'c3',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'view_header' => array( 'type' => 'view_header' ),
'view_back_list' => array( 'type' => 'view_back_list' ),
'view_close' => array( 'type' => 'view_close' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'view_edit' ) ),
'view_edit' => array( 'type' => 'view_edit' ),
'integrated_edit_field' => array( 'field' => 'tipo_proceso_fk',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field15' => array( 'field' => 'id_oaj',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field30' => array( 'field' => 'carpeta',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field31' => array( 'field' => 'CAJA',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field29' => array( 'field' => 'ekogui_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field28' => array( 'field' => 'fecha_radicado_ekogui',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field27' => array( 'field' => 'radicado_ekogui',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field26' => array( 'field' => 'fecha_proxima_actualizacion',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field25' => array( 'field' => 'observacion_perder_caso',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field24' => array( 'field' => 'propabilidad_perder_caso',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field23' => array( 'field' => 'valor_provision_contable',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field22' => array( 'field' => 'fecha_provision_contable',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field21' => array( 'field' => 'etapa_judicial',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field20' => array( 'field' => 'fecha_constestacion_demanda',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field19' => array( 'field' => 'contestacion_demanda',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field18' => array( 'field' => 'fecha_radicado_oaj',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field17' => array( 'field' => 'fecha_admision_demanda',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field16' => array( 'field' => 'apoderado_oaj',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field13' => array( 'field' => 'cuantia_pretension',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field12' => array( 'field' => 'pretenciones',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field11' => array( 'field' => 'fecha_presentacion_demanda',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field10' => array( 'field' => 'despacho_actual',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field9' => array( 'field' => 'nom_demandado',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field8' => array( 'field' => 'apoderado_demandante',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field7' => array( 'field' => 'nom_demandante',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'doc_demandante',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'causas',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field4' => array( 'field' => 'municipio_fk',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field3' => array( 'field' => 'hechos',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field2' => array( 'field' => 'estado_id_fk',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field14' => array( 'field' => 'calidad',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'menu' => array( 'type' => 'menu' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'logout_link' => array( 'type' => 'logout_link' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'logo1' => array( 'type' => 'logo' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'integrated_edit_field1' => array( 'field' => 'num_proceso',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field32' => array( 'field' => 'estado_proceso',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>