<?php
			$optionsArray = array( 'totals' => array( 'oj_id' => array( 'totalsType' => '' ),
'id_oaj' => array( 'totalsType' => '' ),
'tipo_proceso_fk' => array( 'totalsType' => '' ),
'num_proceso' => array( 'totalsType' => '' ),
'estado_id_fk' => array( 'totalsType' => '' ),
'hechos' => array( 'totalsType' => '' ),
'municipio_fk' => array( 'totalsType' => '' ),
'causas' => array( 'totalsType' => '' ),
'doc_demandante' => array( 'totalsType' => '' ),
'nom_demandante' => array( 'totalsType' => '' ),
'apoderado_demandante' => array( 'totalsType' => '' ),
'nom_demandado' => array( 'totalsType' => '' ),
'despacho_actual' => array( 'totalsType' => '' ),
'fecha_presentacion_demanda' => array( 'totalsType' => '' ),
'pretenciones' => array( 'totalsType' => '' ),
'cuantia_pretension' => array( 'totalsType' => '' ),
'cuantia_pretension_index' => array( 'totalsType' => '' ),
'apoderado_oajtemp' => array( 'totalsType' => '' ),
'apoderado_oaj' => array( 'totalsType' => '' ),
'fecha_admision_demanda' => array( 'totalsType' => '' ),
'fecha_radicado_oaj' => array( 'totalsType' => '' ),
'contestacion_demanda' => array( 'totalsType' => '' ),
'fecha_constestacion_demanda' => array( 'totalsType' => '' ),
'etapa_judicial' => array( 'totalsType' => '' ),
'fecha_provision_contable' => array( 'totalsType' => '' ),
'valor_provision_contable' => array( 'totalsType' => '' ),
'propabilidad_perder_caso' => array( 'totalsType' => '' ),
'observacion_perder_caso' => array( 'totalsType' => '' ),
'fecha_proxima_actualizacion' => array( 'totalsType' => '' ),
'radicado_ekogui' => array( 'totalsType' => '' ),
'fecha_radicado_ekogui' => array( 'totalsType' => '' ),
'ekogui_id' => array( 'totalsType' => '' ),
'carpeta' => array( 'totalsType' => '' ),
'CAJA' => array( 'totalsType' => '' ),
'estado_proceso' => array( 'totalsType' => '' ),
'calidad' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'tipo_proceso_fk',
'num_proceso',
'estado_id_fk',
'hechos',
'municipio_fk',
'causas',
'doc_demandante',
'nom_demandante',
'apoderado_demandante',
'nom_demandado',
'despacho_actual',
'fecha_presentacion_demanda',
'pretenciones',
'cuantia_pretension',
'apoderado_oaj',
'fecha_admision_demanda',
'fecha_radicado_oaj',
'contestacion_demanda',
'fecha_constestacion_demanda',
'etapa_judicial',
'fecha_provision_contable',
'valor_provision_contable',
'propabilidad_perder_caso',
'observacion_perder_caso',
'fecha_proxima_actualizacion',
'radicado_ekogui',
'fecha_radicado_ekogui',
'ekogui_id',
'carpeta',
'CAJA',
'estado_proceso',
'id_oaj',
'calidad' ),
'exportFields' => array( 'tipo_proceso_fk',
'num_proceso',
'estado_id_fk',
'hechos',
'municipio_fk',
'causas',
'doc_demandante',
'nom_demandante',
'apoderado_demandante',
'nom_demandado',
'despacho_actual',
'fecha_presentacion_demanda',
'pretenciones',
'cuantia_pretension',
'apoderado_oaj',
'fecha_admision_demanda',
'fecha_radicado_oaj',
'contestacion_demanda',
'fecha_constestacion_demanda',
'etapa_judicial',
'fecha_provision_contable',
'valor_provision_contable',
'propabilidad_perder_caso',
'observacion_perder_caso',
'fecha_proxima_actualizacion',
'radicado_ekogui',
'fecha_radicado_ekogui',
'ekogui_id',
'carpeta',
'CAJA',
'estado_proceso',
'id_oaj',
'calidad' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'tipo_proceso_fk' => array( 'export_field1' ),
'num_proceso' => array( 'export_field2' ),
'estado_id_fk' => array( 'export_field3' ),
'hechos' => array( 'export_field4' ),
'municipio_fk' => array( 'export_field5' ),
'causas' => array( 'export_field6' ),
'doc_demandante' => array( 'export_field7' ),
'nom_demandante' => array( 'export_field8' ),
'apoderado_demandante' => array( 'export_field9' ),
'nom_demandado' => array( 'export_field10' ),
'despacho_actual' => array( 'export_field11' ),
'fecha_presentacion_demanda' => array( 'export_field12' ),
'pretenciones' => array( 'export_field13' ),
'cuantia_pretension' => array( 'export_field14' ),
'apoderado_oaj' => array( 'export_field17' ),
'fecha_admision_demanda' => array( 'export_field18' ),
'fecha_radicado_oaj' => array( 'export_field19' ),
'contestacion_demanda' => array( 'export_field20' ),
'fecha_constestacion_demanda' => array( 'export_field21' ),
'etapa_judicial' => array( 'export_field22' ),
'fecha_provision_contable' => array( 'export_field23' ),
'valor_provision_contable' => array( 'export_field24' ),
'propabilidad_perder_caso' => array( 'export_field25' ),
'observacion_perder_caso' => array( 'export_field26' ),
'fecha_proxima_actualizacion' => array( 'export_field27' ),
'radicado_ekogui' => array( 'export_field28' ),
'fecha_radicado_ekogui' => array( 'export_field29' ),
'ekogui_id' => array( 'export_field30' ),
'carpeta' => array( 'export_field31' ),
'CAJA' => array( 'export_field32' ),
'estado_proceso' => array( 'export_field33' ),
'id_oaj' => array( 'export_field16' ),
'calidad' => array( 'export_field' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field16',
'export_field' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_field28' => 'grid',
'export_field29' => 'grid',
'export_field30' => 'grid',
'export_field31' => 'grid',
'export_field32' => 'grid',
'export_field33' => 'grid',
'export_field16' => 'grid',
'export_field' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field16',
'export_field' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field16',
'export_field' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field1' => array( 'field' => 'tipo_proceso_fk',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'num_proceso',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'estado_id_fk',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'hechos',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'municipio_fk',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'causas',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'doc_demandante',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'nom_demandante',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'apoderado_demandante',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'nom_demandado',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'despacho_actual',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'fecha_presentacion_demanda',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'pretenciones',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'cuantia_pretension',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'apoderado_oaj',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'fecha_admision_demanda',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'fecha_radicado_oaj',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'contestacion_demanda',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'fecha_constestacion_demanda',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'etapa_judicial',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'fecha_provision_contable',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'valor_provision_contable',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'propabilidad_perder_caso',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'observacion_perder_caso',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'fecha_proxima_actualizacion',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'radicado_ekogui',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'fecha_radicado_ekogui',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 'ekogui_id',
'type' => 'export_field' ),
'export_field31' => array( 'field' => 'carpeta',
'type' => 'export_field' ),
'export_field32' => array( 'field' => 'CAJA',
'type' => 'export_field' ),
'export_field33' => array( 'field' => 'estado_proceso',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'id_oaj',
'type' => 'export_field' ),
'export_field' => array( 'field' => 'calidad',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>