<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'ordinal_id',
'procedencia',
'radicado',
'recepcion_fecha',
'razon_social_nombre',
'asunto',
'asignado',
'tipo_fk',
'tema_fk',
'fecha_control',
'fecha_respuesta',
'estado_entrega_fk',
'observaciones',
'sys_user',
'asignado_email' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'ordinal_id' => array( 'import_field' ),
'procedencia' => array( 'import_field1' ),
'radicado' => array( 'import_field2' ),
'recepcion_fecha' => array( 'import_field4' ),
'razon_social_nombre' => array( 'import_field5' ),
'asunto' => array( 'import_field6' ),
'asignado' => array( 'import_field7' ),
'tipo_fk' => array( 'import_field8' ),
'tema_fk' => array( 'import_field9' ),
'fecha_control' => array( 'import_field10' ),
'fecha_respuesta' => array( 'import_field11' ),
'estado_entrega_fk' => array( 'import_field12' ),
'observaciones' => array( 'import_field13' ),
'sys_user' => array( 'import_field14' ),
'asignado_email' => array( 'import_field15' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'ordinal_id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'procedencia',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'radicado',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'recepcion_fecha',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'razon_social_nombre',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'asunto',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'asignado',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'tipo_fk',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'tema_fk',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'fecha_control',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'fecha_respuesta',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'estado_entrega_fk',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'observaciones',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'sys_user',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'asignado_email',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>