<?php
			$optionsArray = array( 'totals' => array( 'ordinal_id' => array( 'totalsType' => '' ),
'procedencia' => array( 'totalsType' => '' ),
'radicado' => array( 'totalsType' => '' ),
'radicado_fecha' => array( 'totalsType' => '' ),
'recepcion_fecha' => array( 'totalsType' => '' ),
'razon_social_nombre' => array( 'totalsType' => '' ),
'asunto' => array( 'totalsType' => '' ),
'asignado' => array( 'totalsType' => '' ),
'asignado_email' => array( 'totalsType' => '' ),
'sc_color' => array( 'totalsType' => '' ),
'tipo_fk' => array( 'totalsType' => '' ),
'tema_fk' => array( 'totalsType' => '' ),
'fecha_control' => array( 'totalsType' => '' ),
'fecha_respuesta' => array( 'totalsType' => '' ),
'estado_entrega_fk' => array( 'totalsType' => '' ),
'observaciones' => array( 'totalsType' => '' ),
'sys_user' => array( 'totalsType' => '' ),
'sys_date' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'ordinal_id',
'procedencia',
'radicado',
'recepcion_fecha',
'razon_social_nombre',
'asunto',
'asignado',
'tipo_fk',
'tema_fk',
'fecha_control',
'fecha_respuesta',
'estado_entrega_fk',
'observaciones',
'sys_user',
'asignado_email' ),
'exportFields' => array( 'ordinal_id',
'procedencia',
'radicado',
'recepcion_fecha',
'razon_social_nombre',
'asunto',
'asignado',
'tipo_fk',
'tema_fk',
'fecha_control',
'fecha_respuesta',
'estado_entrega_fk',
'observaciones',
'sys_user',
'asignado_email' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'ordinal_id' => array( 'export_field' ),
'procedencia' => array( 'export_field1' ),
'radicado' => array( 'export_field2' ),
'recepcion_fecha' => array( 'export_field4' ),
'razon_social_nombre' => array( 'export_field5' ),
'asunto' => array( 'export_field6' ),
'asignado' => array( 'export_field7' ),
'tipo_fk' => array( 'export_field8' ),
'tema_fk' => array( 'export_field9' ),
'fecha_control' => array( 'export_field10' ),
'fecha_respuesta' => array( 'export_field11' ),
'estado_entrega_fk' => array( 'export_field12' ),
'observaciones' => array( 'export_field13' ),
'sys_user' => array( 'export_field14' ),
'asignado_email' => array( 'export_field15' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'ordinal_id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'procedencia',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'radicado',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'recepcion_fecha',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'razon_social_nombre',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'asunto',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'asignado',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'tipo_fk',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'tema_fk',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'fecha_control',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'fecha_respuesta',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'estado_entrega_fk',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'observaciones',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'sys_user',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'asignado_email',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>